# Master Makefile for Tests directory
#

all:
	( cd test1; make )
	( cd test2; make )
	( cd test3; make )
	( cd test4; make )
	( cd test5; make )
	( cd test6; make )
	( cd test7; make )
	( cd test8; make )
	( cd test9; make )

test1:
	( cd test1; make )
test2:
	( cd test2; make )
test3:
	( cd test3; make )
test4:
	( cd test4; make )
test5:
	( cd test5; make )
test6:
	( cd test6; make )
test7:
	( cd test6; make )
test8:
	( cd test6; make )
test9:
	( cd test6; make )
clean:
	( cd test1; make clean )
	( cd test2; make clean )
	( cd test3; make clean )
	( cd test4; make clean )
	( cd test5; make clean )
	( cd test6; make clean )
	( cd test7; make clean )
	( cd test8; make clean )
	( cd test9; make clean )
